metadata:
  annotations:
    configmap.fabric8.io/update-on-change: bootadminstep5
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: demo1
            items:
            - key: application.properties
              path: application.properties
      containers:
        - volumeMounts:
            - name: config
              mountPath: /usr/src/app/config