apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: demo3
  name: demo3
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'demo3-images:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /code/spring-boot-demo0
    git:
      uri: 'https://github.com/atsticks/docker-workshop.git'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'springboot-maven3-centos:latest'
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - imageChange:
        lastTriggeredImageID: >-
          codecentric/springboot-maven3-centos@sha256:b39d58f7beaf97c68047f82a45f74ee1173d162d36f066caa5f11496629f7b13
      type: ImageChange
    - type: ConfigChange