apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    description: Defines how to deploy the application server
  name: demo3
spec:
  replicas: 1
  selector:
     deployment-config.name: demo3
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
         deployment-config.name: demo3
    spec:
      containers:
      - name: demo3
        image: '172.30.1.1:5000/myproject/demo3:latest'
        livenessProbe:
          httpGet:
            path: /hello/healthcheck
            port: 8090
          initialDelaySeconds: 30
          timeoutSeconds: 3
        ports:
        - containerPort: 8090
        readinessProbe:
          httpGet:
            path: /hello/healthcheck
            port: 8090
          initialDelaySeconds: 3
          timeoutSeconds: 3
  triggers:
  - imageChangeParams:
      automatic: false
      containerNames:
      - demo3
      from:
        kind: ImageStreamTag
        name: demo3:latest
    type: ImageChange
  - type: ConfigChange
