version: '2'
services:
  redis:
    image: redis:alpine
  web:
    build: .
    ports:
      - "8088:3000"
    depends_on:
      - redis
  web2:
      build: .
      ports:
        - "8089:3000"
      depends_on:
        - redis